# Generated by Django 4.2.6 on 2024-03-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField()),
                ('preview', models.CharField(max_length=200)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
